package com.asterexcrisys.brainfuck.models.instructions;

@SuppressWarnings("unused")
public record Instruction(String alias, InstructionType type) {

    // All necessary methods are generated by default

}